version: '3'
services:
    pq:
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - "./db/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql"
    mongo-seed:
        build: ./db/mongo-seed
    mongo:
        image: mongo
        ports:
            - "27017:27017"
